using System;
using System.IO;
using System.Threading.Tasks;
using FunFair.BuildCheck.Interfaces;
using FunFair.BuildCheck.SolutionChecks.Tests.Helpers;
using FunFair.Test.Common;
using Microsoft.Extensions.Logging;
using Xunit;

namespace FunFair.BuildCheck.SolutionChecks.Tests;

public sealed class NoOrphanedProjectsExistTests : TestBase
{
    [Fact]
    public async Task WhenSolutionFileHasNoDirectoryLogsErrorAsync()
    {
        CapturingLogger<NoOrphanedProjectsExist> logger = new();
        NoOrphanedProjectsExist check = new(projects: [], logger: logger);

        await check.CheckAsync(solutionFileName: "Solution.slnx", cancellationToken: this.CancellationToken());

        Assert.Single(collection: logger.Entries, predicate: e => e.Level == LogLevel.Error);
    }

    [Fact]
    public async Task WhenAllProjectFilesAreInSolutionNoErrorIsLoggedAsync()
    {
        string tempDir = CreateTempDirectory();

        try
        {
            string projectFile = Path.Combine(path1: tempDir, path2: "Sample.csproj");
            await File.WriteAllTextAsync(
                path: projectFile,
                contents: "<Project />",
                cancellationToken: this.CancellationToken()
            );

            SolutionProject[] projects = [new(fileName: projectFile, displayName: "Sample")];
            CapturingLogger<NoOrphanedProjectsExist> logger = new();
            NoOrphanedProjectsExist check = new(projects: projects, logger: logger);

            await check.CheckAsync(
                solutionFileName: Path.Combine(path1: tempDir, path2: "Solution.slnx"),
                cancellationToken: this.CancellationToken()
            );

            Assert.DoesNotContain(collection: logger.Entries, filter: e => e.Level == LogLevel.Error);
        }
        finally
        {
            Directory.Delete(path: tempDir, recursive: true);
        }
    }

    [Fact]
    public async Task WhenProjectFileIsNotInSolutionErrorIsLoggedAsync()
    {
        string tempDir = CreateTempDirectory();

        try
        {
            string projectFile = Path.Combine(path1: tempDir, path2: "Orphaned.csproj");
            await File.WriteAllTextAsync(
                path: projectFile,
                contents: "<Project />",
                cancellationToken: this.CancellationToken()
            );

            CapturingLogger<NoOrphanedProjectsExist> logger = new();
            NoOrphanedProjectsExist check = new(projects: [], logger: logger);

            await check.CheckAsync(
                solutionFileName: Path.Combine(path1: tempDir, path2: "Solution.slnx"),
                cancellationToken: this.CancellationToken()
            );

            Assert.Single(collection: logger.Entries, predicate: e => e.Level == LogLevel.Error);
        }
        finally
        {
            Directory.Delete(path: tempDir, recursive: true);
        }
    }

    [Fact]
    public async Task WhenAutogeneratedProjectExistsItIsIgnoredAsync()
    {
        string tempDir = CreateTempDirectory();

        try
        {
            string autogenFile = Path.Combine(path1: tempDir, path2: "Generated.Autogenerated.csproj");
            await File.WriteAllTextAsync(
                path: autogenFile,
                contents: "<Project />",
                cancellationToken: this.CancellationToken()
            );

            CapturingLogger<NoOrphanedProjectsExist> logger = new();
            NoOrphanedProjectsExist check = new(projects: [], logger: logger);

            await check.CheckAsync(
                solutionFileName: Path.Combine(path1: tempDir, path2: "Solution.slnx"),
                cancellationToken: this.CancellationToken()
            );

            Assert.DoesNotContain(collection: logger.Entries, filter: e => e.Level == LogLevel.Error);
        }
        finally
        {
            Directory.Delete(path: tempDir, recursive: true);
        }
    }

    private static string CreateTempDirectory()
    {
        string path = Path.Combine(path1: Path.GetTempPath(), path2: Path.GetRandomFileName());
        Directory.CreateDirectory(path);

        return path;
    }
}
